baseurl = "https://datentrang.netlify.com/"
languageCode = "en-us"
title = "Datentrang"
theme = "Mainroad" # https://themes.gohugo.io/mainroad/
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Who am I?"
    url = "http://www.linkedin.com/in/oliver-pfaffel-155205118"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/o1iv3r"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/oliverpfaffel"
[[menu.main]]
    name = "About"
    url = "/about/"

[params]
    subtitle = "R, data and staticial methods"
    description = "A website built around R, data and staticial / machine learning methods"
    toc = true # Enable Table of Contents
    post_navigation = true # Show post navigation at bottom of pages if true
    copyright = "Oliver Pfaffel"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    
[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["recent", "categories", "taglist"]
  
[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

